name: sonarqube

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "develop" ]

jobs:
  sonar-analysis:
    name: Analyze SnackTech
    runs-on: ubuntu-latest
    env:
      MAIL_USER: user
      MAIL_PASS: pass

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Run tests and generate lcov
        run: |
          pytest --cov=. --cov-report=xml:coverage.xml

      - name: Confirm coverage.lcov
        run: |
          ls -l coverage.lcov
          grep SF: coverage.lcov
      
      - name: Runs SonarQube Scanner
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}